package com.chinasoft.employee.dao.entity;

import java.util.Date;

public class RMOneEmployeeDBPerformance {
    /**
    *
    * This field was generated by MyBatis Generator. This field corresponds to
    * the database column t_employee.EMPLOYEE_ID
    *
    * @mbg.generated Thu Mar 14 14:30:12 CST 2019
    */
   private String employeeId;
   /**
   * 
   */
   private String staffName;

   private String staffRegion;

   private String eHr;

   private String skill;

   private String role;

   private String subdeptName;

   private String lob;

   private Date entryDate;

   private String nickname;
   
   private String performance;

   private String quarter;
   
   private String year;
   
   public String getEmployeeId() {
       return employeeId;
   }

   public String getStaffName() {
       return staffName;
   }

   public String getStaffRegion() {
       return staffRegion;
   }

   public String geteHr() {
       return eHr;
   }

   public String getSkill() {
       return skill;
   }

   public String getRole() {
       return role;
   }

   public String getLob() {
       return lob;
   }

   public Date getEntryDate() {
       return entryDate;
   }

   public String getNickname() {
       return nickname;
   }

   public void setEmployeeId(String employeeId) {
       this.employeeId = employeeId;
   }

   public void setStaffName(String staffName) {
       this.staffName = staffName;
   }

   public void setStaffRegion(String staffRegion) {
       this.staffRegion = staffRegion;
   }

   public void seteHr(String eHr) {
       this.eHr = eHr;
   }

   public void setSkill(String skill) {
       this.skill = skill;
   }

   public void setRole(String role) {
       this.role = role;
   }

   public void setLob(String lob) {
       this.lob = lob;
   }

   public void setEntryDate(Date entryDate) {
       this.entryDate = entryDate;
   }

   public void setNickname(String nickname) {
       this.nickname = nickname;
   }

   
   public String getSubdeptName() {
       return subdeptName;
   }

   public void setSubdeptName(String subdeptName) {
       this.subdeptName = subdeptName;
   }

public String getPerformance() {
    return performance;
}

public String getQuarter() {
    return quarter;
}

public String getYear() {
    return year;
}

public void setPerformance(String performance) {
    this.performance = performance;
}

public void setQuarter(String quarter) {
    this.quarter = quarter;
}

public void setYear(String year) {
    this.year = year;
}
   
   
}
