package com.chinasoft.employee.dao.entity;

import java.util.Date;

public class RMOneEmployeeDBDEtails {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column t_employee.EMPLOYEE_ID
     *
     * @mbg.generated Thu Mar 14 14:30:12 CST 2019
     */
    private String employeeId;
    /**
    * 
    */
    private String staffName;

    private String staffRegion;

    private String eHr;

    private String skill;

    private String skillLevel;

    private String subdeptName;

    private String lob;

    private Date entryDate;

    private String rmName;
    
    private String subdeptManager;
    
    

    public String getSubdeptManager() {
        return subdeptManager;
    }

    public void setSubdeptManager(String subdeptManager) {
        this.subdeptManager = subdeptManager;
    }

    public String getEmployeeId() {
        return employeeId;
    }

    public String getStaffName() {
        return staffName;
    }

    public String getStaffRegion() {
        return staffRegion;
    }

    public String geteHr() {
        return eHr;
    }

    public String getSkill() {
        return skill;
    }


    public String getLob() {
        return lob;
    }

    public Date getEntryDate() {
        return entryDate;
    }

    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    public void setStaffRegion(String staffRegion) {
        this.staffRegion = staffRegion;
    }

    public void seteHr(String eHr) {
        this.eHr = eHr;
    }

    public void setSkill(String skill) {
        this.skill = skill;
    }


    public void setLob(String lob) {
        this.lob = lob;
    }

    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    
    public String getSubdeptName() {
        return subdeptName;
    }

    public void setSubdeptName(String subdeptName) {
        this.subdeptName = subdeptName;
    }

    public String getSkillLevel() {
        return skillLevel;
    }

    public void setSkillLevel(String skillLevel) {
        this.skillLevel = skillLevel;
    }

    public String getRmName() {
        return rmName;
    }

    public void setRmName(String rmName) {
        this.rmName = rmName;
    }
    
    
    
}
